[CmdletBinding()]
param([string]$SessionPath,[string]$OutputPath,[switch]$SelfTest)
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'
function Prop($o,[string[]]$n){foreach($x in $n){$p=$o.PSObject.Properties[$x];if($p -and $null -ne $p.Value){return $p.Value}}}
function Text($c){if($null -eq $c){return $null};if($c -is [string]){return $c};if($c -is [System.Collections.IEnumerable]){$a=foreach($i in $c){$v=Text (Prop $i @('text','value','content'));if($v -is [string]){$v}};if($a){return $a -join ''}};$v=Prop $c @('text','value','content');if($v -is [string]){return $v};if($null -ne $v){return Text $v};return $null}
function Records($path){foreach($line in Get-Content -LiteralPath $path){if([string]::IsNullOrWhiteSpace([string]$line)){continue};try{$o=([string]$line)|ConvertFrom-Json}catch{continue};$payload=Prop $o @('payload');$source=if($null -ne $payload){$payload}else{$o};$type=[string](Prop $source @('type','record_type','kind'));$role=[string](Prop $source @('role','author_role'));$delegationInput=Prop $source @('input','delegation_input');$msg=Prop $source @('message','content','text');if($type -match 'delegat|realtime' -and $null -ne $delegationInput){$t=[string]$delegationInput;if($t -match '(?s)<input>(.*?)</input>'){$t=([string]$Matches[1]).Trim()};if(-not [string]::IsNullOrWhiteSpace([string]$t)){[pscustomobject]@{Role='User';Text=$t}};continue};if($o.type -eq 'event_msg' -and $source.type -eq 'user_message'){continue};if($o.type -ne 'response_item' -and $type -notmatch 'delegat|realtime|^(user|assistant)[_-]?message$'){continue};$t=Text $msg;if([string]::IsNullOrWhiteSpace([string]$t)){continue};if($role -match '^user$|^human$'){[pscustomobject]@{Role='User';Text=([string]$t).Trim()}}elseif($role -match '^assistant$|^model$'){[pscustomobject]@{Role='Assistant';Text=([string]$t).Trim()}}}}
function Export-Session($path,$dest){$resolved=(Resolve-Path -LiteralPath $path).Path;$stamp=(Get-Item -LiteralPath $resolved).LastWriteTime.ToString('o');$r=@(Records $resolved);if(!$r.Count){throw "No user or assistant conversation records were found in '$resolved'."};$out=[Collections.Generic.List[string]]::new();$out.Add('# Codex Voice session export');$out.Add('');$out.Add("- Source: ``$resolved``");$out.Add("- Source last updated: $stamp");$out.Add("- Exported: $([DateTimeOffset]::Now.ToString('o'))");$out.Add('');foreach($x in $r){$out.Add("## $($x.Role)");$out.Add('');$out.Add($x.Text);$out.Add('')};Set-Content -LiteralPath $dest -Value $out -Encoding utf8;"Wrote $($r.Count) conversation records to $dest"}
if($SelfTest){$r=@(Records (Join-Path $PSScriptRoot 'work\fixture.jsonl'));$t=@($r|% Text);if($r.Count -ne 3 -or $r[0].Text -ne 'Plan the exporter' -or $r[1].Text -ne 'Use the actual input value.' -or $r[2].Text -ne 'Plan the exporter' -or ($t -contains 'delta wrapper noise')){throw "Self-test failed: $($t -join ' | ')"};'Self-test passed: 3 records extracted; wrapper/event noise omitted.';exit}
if(!$SessionPath){$root=[IO.Path]::Combine($env:USERPROFILE,'.codex','sessions');$c=Get-ChildItem -LiteralPath $root -Filter '*.jsonl' -File -Recurse|Sort-Object LastWriteTime -Descending|Select-Object -First 1;if(!$c){throw "No JSONL session logs found under '$root'."};$SessionPath=$c.FullName};if(!$OutputPath){$OutputPath=Join-Path (Get-Location) 'codex-voice-session.md'};Export-Session $SessionPath $OutputPath
